permissions:
  deployments: write
  contents: read

name: Cleanup Old Deployments

on:
  deployment_status:

jobs:
  clean-up:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Delete old deployments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            if (deployments.data.length > 1) {
              for (let i = 1; i < deployments.data.length; i++) {
                await github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployments.data[i].id,
                });
              }
            }
